# Generated by Django 2.0.5 on 2018-05-18 13:58

import stdimage.validators
from django.db import migrations

import website.models_auxiliary


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True,
                                                upload_to=website.models_auxiliary.CustomUploadTo(path='',
                                                                                                  random_filename=True,
                                                                                                  upload_type='images'),
                                                validators=[stdimage.validators.MaxSizeValidator(1500, 1500)]),
        ),
    ]
