# Generated by Django 2.0.5 on 2018-06-12 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0005_auto_20180608_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='cost_sum',
            field=models.IntegerField(default=0),
        ),
    ]
