# Generated by Django 2.0.5 on 2018-06-12 17:35

from django.db import migrations, models

import website.models_auxiliary


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0007_auto_20180612_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(
                upload_to=website.models_auxiliary.CustomUploadTo(append_random=True, path='', upload_type='files')),
        ),
    ]
