# Generated by Django 2.0.5 on 2018-06-12 18:18

from django.db import migrations, models

import website.models_auxiliary


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0008_auto_20180612_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=website.models_auxiliary.CustomFileField(
                upload_to=website.models_auxiliary.CustomUploadTo(append_random=True, path='', upload_type='files')),
        ),
    ]
