# Generated by Django 2.0.5 on 2018-06-16 19:53

from django.db import migrations

default_tag_names = sorted([
    'crypto',
    'stego',
    'pwn',
    'ppc',
    'reverse',
    'forensics',
    'recon',
    'admin',
    'misc',
])


def create_default_tags(apps, schema_editor):
    TaskTag = apps.get_model('website', 'TaskTag')
    for tag_name in default_tag_names:
        tag = TaskTag(name=tag_name)
        tag.save()


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0012_auto_20180616_2253'),
    ]

    operations = [
        migrations.RunPython(create_default_tags)
    ]
