# Generated by Django 2.0.5 on 2018-06-17 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0013_auto_20180616_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('view_task', 'View task'), ('create_task', 'Create task'))},
        ),
    ]
