# Generated by Django 2.0.5 on 2018-06-17 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0014_auto_20180617_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('view_task', 'View task'),)},
        ),
    ]
