# Generated by Django 2.0.5 on 2018-06-17 10:40

from django.db import migrations


def create_administrators_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Administrators')


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0015_auto_20180617_1337'),
    ]

    operations = [
        migrations.RunPython(create_administrators_group)
    ]
