# Generated by Django 2.0.5 on 2018-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0020_auto_20180617_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_tasks_archive', "Can view user's tasks archive"),
                                     ('view_contests_archive', "Can view user's contests archive"))},
        ),
        migrations.AddField(
            model_name='contest',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
