# Generated by Django 2.0.5 on 2018-06-18 07:23

from django.contrib.auth.management import create_permissions
from django.db import migrations


def migrate_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def all_permissions_for_admins(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    permissions = list(Permission.objects.all())
    administrators = Group.objects.get(name='Administrators')
    administrators.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0022_auto_20180618_0916'),
    ]

    operations = [
        #migrations.RunPython(migrate_permissions),
        #migrations.RunPython(all_permissions_for_admins)
    ]
