# Generated by Django 2.0.5 on 2018-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0024_auto_20180618_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
