# Generated by Django 2.0.5 on 2018-06-18 08:59

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0024_auto_20180618_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
