# Generated by Django 2.0.5 on 2018-06-19 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0025_auto_20180618_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cost_sum',
        ),
    ]
