# Generated by Django 2.0.5 on 2018-06-20 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0026_remove_user_cost_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (
                ('view_task', 'Can view task'), ('view_who_solved_task', 'Can view list of users who solved task'))},
        ),
    ]
