# Generated by Django 2.0.5 on 2018-06-21 14:14

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0028_auto_20180620_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
