# Generated by Django 2.0.5 on 2018-06-21 14:19

from django.contrib.auth.management import create_permissions
from django.db import migrations


def migrate_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def remove_who_solved_task_view_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    view_task_perm = Permission.objects.get(codename='view_who_solved_task')
    view_task_perm.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0030_user_last_solve'),
    ]

    operations = [
        #migrations.RunPython(migrate_permissions),
        #migrations.RunPython(remove_who_solved_task_view_permission)
    ]
