# Generated by Django 2.0.5 on 2018-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0031_auto_20180621_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='celery_end_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='celery_start_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
