# Generated by Django 2.0.5 on 2018-06-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0032_auto_20180621_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
