# Generated by Django 2.0.5 on 2018-06-22 08:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0033_contest_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='publication_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 11, 28, 38)),
        ),
    ]
