# Generated by Django 2.0.5 on 2018-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0034_task_publication_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contest',
        ),
        migrations.AddField(
            model_name='contest',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='contests', to='website.Task'),
        ),
    ]
