# Generated by Django 2.0.5 on 2018-06-26 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0035_auto_20180622_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestParticipantRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestTaskRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contest',
            name='tasks',
        ),
        migrations.AddField(
            model_name='contest',
            name='tasks',
            field=models.ManyToManyField(blank=True,
                                         related_name='contests',
                                         through='website.ContestTaskRelationship',
                                         to='website.Task'),
        ),
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Contest'),
        ),
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Task'),
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Contest'),
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contests_participants_relationship', to='website.Task'),
        ),
        migrations.AddField(
            model_name='contestparticipantrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='contests_participated',
                                         through='website.ContestParticipantRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
