# Generated by Django 2.0.5 on 2018-06-26 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0036_auto_20180626_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestparticipantrelationship',
            name='is_solved',
        ),
        migrations.RemoveField(
            model_name='contestparticipantrelationship',
            name='task',
        ),
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='number_solves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='solved',
            field=models.ManyToManyField(blank=True, related_name='contests_tasks_solved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
