# Generated by Django 2.0.5 on 2018-06-26 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0037_auto_20180626_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestparticipantrelationship',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestparticipantrelationship',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='contests_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ContestParticipantRelationship',
        ),
    ]
