# Generated by Django 2.0.5 on 2018-06-27 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0038_auto_20180626_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttaskrelationship',
            name='number_solves',
        ),
    ]
