# Generated by Django 2.0.5 on 2018-06-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0039_remove_contesttaskrelationship_number_solves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_relationship',
                                    to='website.Task'),
        ),
    ]
