# Generated by Django 2.0.5 on 2018-06-27 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0042_contest_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTaskUpsolvingRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='contest_task_upsolving_relationship',
                                              to='website.Contest')),
                ('solved', models.ManyToManyField(blank=True, related_name='contests_tasks_upsolving_relationship',
                                                  to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='contest_task_upsolving_relationship', to='website.Task')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='upsolving_tasks',
            field=models.ManyToManyField(blank=True, related_name='contests_upsolving',
                                         through='website.ContestTaskUpsolvingRelationship', to='website.Task'),
        ),
    ]
