# Generated by Django 2.0.5 on 2018-06-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20180627_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttaskrelationship',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_task_relationships', to='website.TaskTag'),
        ),
        migrations.AddField(
            model_name='contesttaskupsolvingrelationship',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_task_upsolving_relationships', to='website.TaskTag'),
        ),
    ]
