# Generated by Django 2.0.5 on 2018-06-28 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0044_auto_20180628_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('view_unstarted_contest', 'Can view not started contest'),)},
        ),
    ]
