# Generated by Django 2.0.5 on 2018-06-28 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0047_auto_20180628_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='solved',
            field=models.ManyToManyField(blank=True, related_name='contest_tasks_relationship',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
