# Generated by Django 2.0.5 on 2018-06-28 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0048_auto_20180628_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='solved',
            field=models.ManyToManyField(blank=True, related_name='contest_task_relationship',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contesttaskrelationship',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contest_task_relationship', to='website.TaskTag'),
        ),
        migrations.AlterField(
            model_name='contesttaskupsolvingrelationship',
            name='solved',
            field=models.ManyToManyField(blank=True, related_name='contest_task_upsolving_relationship',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contesttaskupsolvingrelationship',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contest_task_upsolving_relationship', to='website.TaskTag'),
        ),
    ]
