# Generated by Django 2.0.5 on 2018-06-28 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0049_auto_20180628_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='upsolving_participants',
            field=models.ManyToManyField(blank=True, related_name='contests_upsolving_participated',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
