# Generated by Django 2.0.5 on 2018-06-28 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0050_auto_20180628_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttaskupsolvingrelationship',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contesttaskupsolvingrelationship',
            name='solved',
        ),
        migrations.RemoveField(
            model_name='contesttaskupsolvingrelationship',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='contesttaskupsolvingrelationship',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('view_unstarted_contest', 'Can view not started contest'),
                                     ('view_running_contest', 'Can view running contest'))},
        ),
        migrations.RemoveField(
            model_name='contest',
            name='upsolving_participants',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='upsolving_tasks',
        ),
        migrations.DeleteModel(
            name='ContestTaskUpsolvingRelationship',
        ),
    ]
