# Generated by Django 2.0.5 on 2018-07-01 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0052_auto_20180628_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_processed',
        ),
    ]
