# Generated by Django 2.0.5 on 2018-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0053_remove_user_avatar_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_rating',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=2000),
        ),
    ]
