# Generated by Django 2.1b1 on 2018-07-05 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0054_auto_20180701_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('view_who_solved_task', 'Can view list of users who solved task'),)},
        ),
    ]
