# Generated by Django 2.1.1 on 2018-09-21 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0056_auto_20180921_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('view_unstarted_contest', 'Can view not started contest'),
                                     ('can_participate_in_contest', 'Can participate in contest'))},
        ),
    ]
